export default [
  {label: 'People', handle:'PERSON'},
  {label: 'Words', handle:'tokens'},
  {label: 'Authors', handle:'author'},
  {label: 'Identities', handle:'NORP'},
  {label: 'Buildings', handle:'FAC'},
  {label: 'Organizations', handle:'ORG'},
  {label: 'Political Entities', handle:'GPE'},
  {label: 'Locations', handle:'LOC'},
  {label: 'Products', handle:'PRODUCT'},
  {label: 'Events', handle:'EVENT'},
  {label: 'Works of art', handle:'WORK_OF_ART'},
  {label: 'Laws', handle:'LAW'},
  {label: 'Languages', handle:'LANGUAGE'},
  {label: 'Dates', handle:'DATE'},
  {label: 'Time', handle:'TIME'},
  {label: 'Percentage', handle:'PERCENT'},
  {label: 'Money', handle:'MONEY'},
  {label: 'Quantity', handle:'QUANTITY'},
  {label: 'Ordinal', handle:'ORDINAL'},
  {label: 'Cardinal', handle:'CARDINAL'}
]